version: "3.7"

services:
  api-tests:
    image: tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "pytest --alluredir=allure-results"
    working_dir: /usr/workspace

  report:
    image: tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "allure serve results --clean -o report"
    working_dir: /usr/workspace